# Generated by Django 3.2 on 2021-04-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(default='Django에서 보낸 메시지 입니다.')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
