# Generated by Django 3.2 on 2021-04-11 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_auto_20210410_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='like',
        ),
    ]
