# Generated by Django 3.2 on 2021-04-11 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0004_auto_20210411_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='like_user_set',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
